### ISSUE TITLE
Outdated Install Guide for Environmental Variables

### ISSUE THREAD

**Issue by snub-fighter** [interledger4j/java-ilpv4-connector-docs#10]
Took me a few minutes to figure this out.  You are requesting the latest openjdk version be installed here.  [Install OpenJDK 8](https://github.com/sappenin/java-ilpv4-connector-docs/blob/master/tutorials/install-the-connector-debian.md#install-openjdk-8)  

**However the default-jdk is now 11 for Ubuntu 18.04.**  

A note in here clarifying that this can be skipped if using a version later than 8 [JCE Policy](https://www.oracle.com/technetwork/java/javase/downloads/jce-all-download-5170447.html).
```
Current versions of the JDK do not require these policy files. They are provided here for use with older version of the JDK.

JDK 9 and later ship with, and use by default, the unlimited policy files.
```

Checking default-jdk install version 
```
dpkg -s default-jdk | grep Depends
Depends: default-jre (= 2:1.11-68ubuntu1~18.04.1), default-jdk-headless (= 2:1.11-68ubuntu1~18.04.1), openjdk-11-jdk

```

**Comment by sappenin** [comment]
Thanks for filing this issue -- I updated the docs to address this. See here: https://java-connector.ilpv4.dev/tutorials/install-the-connector-debian#install-openjdk-8

I'm going to close this issue as fixed - plz re-open if you see anything I missed.
