### ISSUE TITLE
Adding Accounts to default configuration

### ISSUE THREAD

**Issue by snub-fighter** [interledger4j/java-ilpv4-connector-docs#11]
It is unclear to me where the peer account information is to be added into the [application.yml file](https://github.com/sappenin/java-ilpv4-connector-docs/blob/master/tutorials/starting-the-connector.md#default-configuration).
Alice must know about Bob but there is a disconnect as to where the peer information should belong.

An summary example application.yml file **with the ILP ping + peer accounts** would be really helpful in this section.
[Peering: ILP-over-HTTP
](https://github.com/sappenin/java-ilpv4-connector-docs/blob/master/tutorials/peering-ilp-over-http.md#peering-ilp-over-http)

**Comment by sappenin** [comment]
Hi @snub-fighter thanks for your issue.

In the Java Connector, peering is not done via the yaml file (this is a departure from the JS style). In the Java Connector, all admin functionality, including creating new accounts, is performed via the admin API.

Unfortunately this isn't very well documented in the [Peering](https://java-connector.ilpv4.dev/tutorials/peering-ilp-over-http) docs, but the [Admin API](https://java-connector.ilpv4.dev/api-references/admin-api) section should give you an idea of how to create new accounts for peering.

Note that this API will change slightly once https://github.com/hyperledger/quilt/issues/383 is completed and integrated into the Connector (that will be part of the 0.2 release).

**Comment by sappenin** [comment]
Closing this in-favor of #12
