### ISSUE TITLE
Update Install Script for JAVA_HOME variable

### ISSUE THREAD

**Issue by snub-fighter** [interledger4j/java-ilpv4-connector-docs#13]
**Describe the bug**
After identifying that Ubuntu 18.04 default-jdk uses jdk11 the JAVA_HOME export command is skipped because it is part of the [JCE Policy Script](https://java-connector.ilpv4.dev/tutorials/install-the-connector-debian#install-unlimited-jce-policy).  This should be moved from [Policy Script](https://java-connector.ilpv4.dev/tutorials/install-the-connector-debian#install-unlimited-jce-policy) to the [Install JDK 8 Section](https://java-connector.ilpv4.dev/tutorials/install-the-connector-debian#install-openjdk-8)

**To Reproduce**
1. Go to '[install openjdk-8](https://java-connector.ilpv4.dev/tutorials/install-the-connector-debian#install-openjdk-8)'
2. Install default-jdk  `sudo apt-get install default-jdk`
3. Attempt to[ install java-ilp-connecter ](https://java-connector.ilpv4.dev/tutorials/install-the-connector-debian#download-and-build)(it will fail due to not having a JAVA_HOME variable)
 **Error** :   `[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.1.1:jar (attach-javadocs) on project connector-ilpv4-api: MavenReportException: Error while generating Javadoc: Unable to find javadoc command: The environment variable JAVA_HOME is not correctly set. -> [Help 1]`

4. **Resolution** : Change code snippet at [Install OpenJDK 8 ](https://java-connector.ilpv4.dev/tutorials/install-the-connector-debian#install-openjdk-8) -> **installOpenJdk8.sh**
```
sudo apt-get update
sudo apt-get install default-jdk
find /usr/lib/jvm/ -regex '^/usr/lib/jvm/java.*-openjdk-amd64$' -type d
#output -> /usr/lib/jvm/java-{VERSION}-openjdk-amd64/
#example -> /usr/lib/jvm/java-11-openjdk-amd64/
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/
```

**Screenshots**
**Error**
![image](https://user-images.githubusercontent.com/5192578/71549962-79d5ea80-297b-11ea-9bb5-fac6d4ad0c43.png)
**Resolution**
![image](https://user-images.githubusercontent.com/5192578/71550006-dd601800-297b-11ea-8b4e-c3729002c8c1.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Comment by sappenin** [comment]
Thanks for submitting this @snub-fighter - this was an excellent description. I've fixed this in the docs per your suggestions (see [here](https://java-connector.ilpv4.dev/tutorials/install-the-connector-debian#install-openjdk-8)). If you see anything missing, please re-open this issue or create a new one.
