### ISSUE TITLE
Additional detail for "Starting the Connector" page

### ISSUE THREAD

**Issue by snub-fighter** [interledger4j/java-ilpv4-connector-docs#14]
There is very little detail covering the post install procedures on the [Starting the Connector ](https://java-connector.ilpv4.dev/tutorials/starting-the-connector#default-configuration)page.

It appears at this stage that it assumes you are still at folder `/srv/java-ilpv4-connector` and you must create a basic application.yml file then run the command at the bottom of the page.

**Reproduced as I interpret this page**  
1. Create the application.yml file using the format provided in the directory `/srv/java-ilpv4-connector`  
2. Run the command `java -jar ilpv4-connector-server-0.1.0-SNAPSHOT-exec.jar`  
3. Receive Error : 
```
user@cns-usa-west:/srv/java-ilpv4-connector# java -jar ilpv4-connector-server-0.1.0-SNAPSHOT-exec.jar
Error: Unable to access jarfile ilpv4-connector-server-0.1.0-SNAPSHOT-exec.jar
```
4. Attempted to find a jar file with a similar or partial name and found none in my entire system

**What I expect**  
Detailed explanation as to where and how this file should be created or modified.  @sappenin had mentioned environmental variables but it is still unclear on proper procedure and how those EVs are connected to the application.yml file. 

1. A very detailed explanation of the yml file, its location and best practice method of configuring it (see # 2) 
2. Explanation on EVs and its relationship + implementation with yml file.  
3. Where this .jar file comes from that is required to run.

**Comment by snub-fighter** [comment]
Per @sappenin request  I looked at the Install Guide again - 6th line of [Download & Build](https://java-connector.ilpv4.dev/tutorials/install-the-connector-debian#download-and-build) doesnt have the .jar file.  

Side note : It is noteworthy that there is an example applicaton.yml file here.

```
cd /srv
git clone https://github.com/sappenin/java-ilpv4-connector.git
cd java-ilpv4-connector
mvn clean install -DskipTests
mkdir /srv/connector-java
mv  /srv/java-ilpv4-connector/ilpv4-connector-server/target/ilpv4-connector-server-0.1.0-SNAPSHOT-exec.jar /srv/connector-java/
```

In reviewing the source I did not see such a filename exists in any capacity, nor the folder it should be under.  David mentioned it should be HEAD-SNAPSHOT and in doing that I found the folder renamed to connector-server.  Im assuming this is correct until told otherwise.
There are multiple issues with the broken command.
1. Incorrect name  
`  ilpv4-connector-server-0.1.0-SNAPSHOT-exec.jar -> connector-server-HEAD-SNAPSHOT-exec.jar
`  
2. Incorrect Path
` /srv/java-ilpv4-connector/ilpv4-connector-server/target/ -> /srv/java-ilpv4-connector/connector-server/target/`  
3. Incorrect destination folder (Per the folder [D&B ](https://java-connector.ilpv4.dev/tutorials/install-the-connector-debian#download-and-build)req'd me to make )
`  /srv/connector-java/ -> /srv/java-ilpv4-connector/`

### Incorrect mv Command
` mv  /srv/java-ilpv4-connector/ilpv4-connector-server/target/ilpv4-connector-server-0.1.0-SNAPSHOT-exec.jar /srv/connector-java/`
### Corrected mv Command
`mv /srv/java-ilpv4-connector/connector-server/target/connector-server-HEAD-SNAPSHOT-exec.jar /srv/java-ilpv4-connector/`

## Final Fix
In discovering the incorrect .jar filename it is now required to change the start command under the [Starting the Connector](https://java-connector.ilpv4.dev/tutorials/starting-the-connector). 
### Incorrect Start Command
`java -jar ilpv4-connector-server-0.1.0-SNAPSHOT-exec.jar`
### Corrected Start Command
`java -jar connector-server-HEAD-SNAPSHOT-exec.jar `

**Comment by sappenin** [comment]
@snub-fighter - Thanks for a great submission!!

This should now be fixed. Please re-open or create a new issue if you find more errors in the docs.
