### ISSUE TITLE
Connector Configuration Properties Update

### ISSUE THREAD

**Issue by dino-rodriguez** [interledger4j/java-ilpv4-connector-docs#16]
* Add pubsub configuration
* Add jks to Spring (breaking if not there)

**Comment by nhartner** [comment]
I updated the git book with the following sections:

- pusub: https://app.gitbook.com/@interledger/s/java-ilp-connector/~/drafts/-LzsK1Fld0qA0mXd6Y8Z/operating-a-connector/configuration#properties-gcp-pub-sub
- jks: created a new profile `insecure` that the Running with Docker section gives an example for using to run a local dev connector. Setting proper JKS keys is covered here: https://app.gitbook.com/@interledger/s/java-ilp-connector/~/drafts/-LzsK1Fld0qA0mXd6Y8Z/operating-a-connector/configuration#properties-jks-key-management
